// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwBN5IwMEZvFYsHXIiAR6GsoaMeJVKcbQ',
    appId: '1:42526084061:web:a017dc0f02a90ae71b4434',
    messagingSenderId: '42526084061',
    projectId: 'uffer-9d3dd',
    authDomain: 'uffer-9d3dd.firebaseapp.com',
    storageBucket: 'uffer-9d3dd.appspot.com',
    measurementId: 'G-TZWX3CTBRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJRzvB8575WLM9atLgwcP9jcMzObKPeRc',
    appId: '1:42526084061:android:fcb63fc7b13f20d51b4434',
    messagingSenderId: '42526084061',
    projectId: 'uffer-9d3dd',
    storageBucket: 'uffer-9d3dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9TQrSaRMO8GUxuNTjayOMbFTq_V6kCLc',
    appId: '1:42526084061:ios:09e769dd29825b821b4434',
    messagingSenderId: '42526084061',
    projectId: 'uffer-9d3dd',
    storageBucket: 'uffer-9d3dd.appspot.com',
    iosBundleId: 'com.example.uffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9TQrSaRMO8GUxuNTjayOMbFTq_V6kCLc',
    appId: '1:42526084061:ios:223af4b4eb5a06b51b4434',
    messagingSenderId: '42526084061',
    projectId: 'uffer-9d3dd',
    storageBucket: 'uffer-9d3dd.appspot.com',
    iosBundleId: 'com.example.uffer.RunnerTests',
  );
}
